# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6c4b2c79db6ae204d46514d5ca44fa8ba4012f45cb5fc1621ecd29c8230753d4767b74bf139006834138bf1f63c35c4705835851dbd8d691c1825f9f8877b1a

test:
  secret_key_base: b03d93a013a0b229f79b9b03a9876ad024335667ede76a86e14f1922c5ed84fa6d38a8c2823b4535f73247de1866ee40fef8b72814559621fa26d19fa75a9cbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
